### ISSUE TITLE
UI: boutons écran de connexions aux équipes

### ISSUE THREAD

**Issue by FrancoisHuguet** [louije/court-message#61]
![Capture d’écran 2023-09-08 à 15 47 22](https://github.com/louije/court-message/assets/28983018/d6a8f624-66cf-4910-962d-da37915ba3f1)

Voir sur le figma. 
Modifier le nom du bouton de connexion et rajouter une icône pour configurer l'équipe

**Comment by FrancoisHuguet** [comment]
@JeanneChiche te notifie sur le figma afin que tu vois ce que tu dois changer.

**Comment by louije** [comment]
Le bouton configurer n'est montré qu'aux admins, pour info.
