### ISSUE TITLE
UI : page de sélection d'équipe

### ISSUE THREAD

**Issue by FrancoisHuguet** [louije/court-message#62]
Rajouter un encadré avec logo et message de bienvenue sur la page d'accueil et de connexion aux équipes de alpha.court-message.fr.

rajouter également un bouton de déconnexion

Cf. figma

**Comment by JeanneChiche** [comment]
<img width="602" alt="Capture d’écran 2023-09-08 à 16 24 57" src="https://github.com/louije/court-message/assets/61736534/dd75435a-a836-4ad4-84d6-5b62ea453152">

**Comment by louije** [comment]
C'est bon. Tous ces écrans sont à revoir -> l'adresse n'a aucun intérêt, alors que des stats sur le nombre de conversations non lues, et les membres, c'est plus intéressant.
Le "toutes les autres équipes" mérite d'être dans des écrans admin.
Mais c'est un _placeholder_ !
