### ISSUE TITLE
Bug : création de compte impossible

### ISSUE THREAD

**Issue by FrancoisHuguet** [louije/court-message#67]
on ne peut pas créer un compte à partir d'une nouvelle adresse mail.

je viens d'essayer avec une nouvelle adresse mail et ça ne fonctionne pas.

**Comment by louije** [comment]
Changer de compte Sendgrid a permis aux emails de fonctionner à nouveau.
En revanche, on a un vilain message "vous n'êtes pas connecté" après avoir créé un compte, au lieu d'un joli "attendez le mail de confirmation". Je vois ce qu'on peut faire.

**Comment by louije** [comment]
Ajout d'une page "attendez et cliquez le lien dans l'email". 

![Image](https://github.com/louije/court-message/assets/614448/7c9bf745-1db5-422d-96e9-c33139a0ab3d)
